In [1]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.preprocessing  import StandardScaler
from sklearn import preprocessing
import nltk
import keras
from keras.utils import to_categorical
from keras.models import Sequential, Model, load_model
from keras import applications
from keras import optimizers
from keras.layers import Dropout, Flatten, Dense
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
from keras.models import load_model
import itertools


ModuleNotFoundError: No module named 'sklearn'

In [2]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.preprocessing  import StandardScaler
from sklearn import preprocessing
import nltk
import keras
from keras.utils import to_categorical
from keras.models import Sequential, Model, load_model
from keras import applications
from keras import optimizers
from keras.layers import Dropout, Flatten, Dense
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
from keras.models import load_model
import itertools


Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [3]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.preprocessing  import StandardScaler
from sklearn import preprocessing
import nltk
import keras
from keras.utils import to_categorical
from keras.models import Sequential, Model, load_model
from keras import applications
from keras import optimizers
from keras.layers import Dropout, Flatten, Dense
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
from keras.models import load_model
import itertools


Using TensorFlow backend.


In [4]:
xdf = pd.read_csv("train_tree.csv")
ydf = pd.read_csv("train_author.csv")


In [5]:
X_train , X_test , y_train , y_test = train_test_split(xdf,ydf['author'],test_size=0.3,random_state=1010)


sc=StandardScaler()

sc.fit(X_train)
x_train_nor=sc.transform(X_train)
x_test_nor=sc.transform(X_test)

print (x_train_nor.shape)
print (x_test_nor.shape)
print (y_train.shape)
print (y_test.shape)

(13705, 141)
(5874, 141)
(13705,)
(5874,)


In [6]:
from keras.utils import to_categorical

for i in range(len(y_train)):
   if y_train[i] == 'EAP':
      y_train[i] = 0
   elif y_train[i] == 'HPL':
      y_train[i] = 1
   elif y_train[i] == 'MWS':
      y_train[i] = 2

print (y_train)

KeyError: 2

In [7]:
from keras.utils import to_categorical

for i in range(len(y_train)):
   if y_train.iloc[i] == 'EAP':
      y_train.iloc[i] = 0
   elif y_train.iloc[i] == 'HPL':
      y_train.iloc[i] = 1
   elif y_train.iloc[i] == 'MWS':
      y_train.iloc[i] = 2

print (y_train)

16457    0
6838     1
13585    2
12095    2
1209     2
        ..
8546     1
4906     0
6851     0
8394     2
18120    0
Name: author, Length: 13705, dtype: int64


In [8]:
y_train = pd.DataFrame(y_train) 
y_train.astype('int')
y_train.info()
print (y_train)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13705 entries, 16457 to 18120
Data columns (total 1 columns):
author    13705 non-null int64
dtypes: int64(1)
memory usage: 854.1 KB
       author
16457       0
6838        1
13585       2
12095       2
1209        2
...       ...
8546        1
4906        0
6851        0
8394        2
18120       0

[13705 rows x 1 columns]


In [9]:
y_train = to_categorical(y_train)
print (y_train)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [10]:
def deep_model(i):
    model = Sequential()
    model.add(Dense(64, input_dim=141, activation='sigmoid'))
    for k in range(i):
      model.add(Dense(64,activation='sigmoid'))
    model.add(Dense(1, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

for lavel in range(1,10):
    model = deep_model(lavel)
    model.fit(x_train_nor, y_train,epochs=25,verbose=1)
    y_test_predicted = model.predict(x_test_nor)
    print(y_test_predicted.shape[0])
    pdct = []
    for i in range(int(y_test_predicted.shape[0])):
        if (y_test_predicted[i,0] > y_test_predicted[i,1]):
            pdct.append(int(0))
        else:
            pdct.append(int(1))
    accuracy = accuracy_score(y_test, pdct)

    print('lavel = ',lavel,'training 準確率:',accuracy)
    

ValueError: Error when checking target: expected dense_3 to have shape (1,) but got array with shape (3,)

In [11]:
def deep_model(i):
    model = Sequential()
    model.add(Dense(64, input_dim=141, activation='sigmoid'))
    for k in range(i):
      model.add(Dense(64,activation='sigmoid'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

for lavel in range(1,10):
    model = deep_model(lavel)
    model.fit(x_train_nor, y_train,epochs=25,verbose=1)
    y_test_predicted = model.predict(x_test_nor)
    print(y_test_predicted.shape[0])
    pdct = []
    for i in range(int(y_test_predicted.shape[0])):
        if (y_test_predicted[i,0] > y_test_predicted[i,1]):
            pdct.append(int(0))
        else:
            pdct.append(int(1))
    accuracy = accuracy_score(y_test, pdct)

    print('lavel = ',lavel,'training 準確率:',accuracy)
    

Epoch 1/25
13705/13705 [==============================] - 1s 49us/step - loss: 0.8942 - accuracy: 0.5831
Epoch 2/25
13705/13705 [==============================] - 0s 36us/step - loss: 0.7751 - accuracy: 0.6542
Epoch 3/25
13705/13705 [==============================] - 1s 37us/step - loss: 0.7639 - accuracy: 0.6598
Epoch 4/25
13705/13705 [==============================] - 0s 36us/step - loss: 0.7570 - accuracy: 0.6617
Epoch 5/25
13705/13705 [==============================] - 0s 34us/step - loss: 0.7534 - accuracy: 0.6660
Epoch 6/25
13705/13705 [==============================] - 0s 32us/step - loss: 0.7489 - accuracy: 0.6668
Epoch 7/25
13705/13705 [==============================] - 0s 33us/step - loss: 0.7433 - accuracy: 0.6680
Epoch 8/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.7399 - accuracy: 0.6716
Epoch 9/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.7342 - accuracy: 0.6741
Epoch 10/25
13705/13705 [==============================

KeyboardInterrupt: 

In [12]:
print (y_test)

11204    EAP
16429    HPL
5729     HPL
10538    HPL
11616    EAP
        ... 
5503     HPL
10422    EAP
10021    HPL
300      MWS
9263     HPL
Name: author, Length: 5874, dtype: object


In [13]:
X_train , X_test , y_train , y_test = train_test_split(xdf,ydf['author'],test_size=0.3,random_state=1010)


sc=StandardScaler()

sc.fit(X_train)
x_train_nor=sc.transform(X_train)
x_test_nor=sc.transform(X_test)

print (x_train_nor.shape)
print (x_test_nor.shape)
print (y_train.shape)
print (y_test.shape)


(13705, 141)
(5874, 141)
(13705,)
(5874,)


In [14]:
from keras.utils import to_categorical

for i in range(len(y_train)):
   if y_train.iloc[i] == 'EAP':
      y_train.iloc[i] = 0
   elif y_train.iloc[i] == 'HPL':
      y_train.iloc[i] = 1
   elif y_train.iloc[i] == 'MWS':
      y_train.iloc[i] = 2
for i in range(len(y_test)):
   if y_test.iloc[i] == 'EAP':
      y_test.iloc[i] = 0
   elif y_test.iloc[i] == 'HPL':
      y_test.iloc[i] = 1
   elif y_test.iloc[i] == 'MWS':
      y_test.iloc[i] = 2


y_train = pd.DataFrame(y_train) 
y_train.astype('int')
y_test = pd.DataFrame(y_test)
y_test.astype('int')

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)



In [15]:
print (y_train)
print (y_test)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [16]:
def deep_model(i):
    model = Sequential()
    model.add(Dense(64, input_dim=141, activation='sigmoid'))
    for k in range(i):
      model.add(Dense(64,activation='sigmoid'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

for lavel in range(1,2):
    model = deep_model(lavel)
    model.fit(x_train_nor, y_train,epochs=25,verbose=1)
    y_test_predicted = model.predict(x_test_nor)
    print(y_test_predicted.shape[0])
   #  pdct = []
   #  for i in range(int(y_test_predicted.shape[0])):
   #      if (y_test_predicted[i,0] > y_test_predicted[i,1]):
   #          pdct.append(int(0))
   #      else:
   #          pdct.append(int(1))
   
    accuracy = accuracy_score(y_test, y_test_predicted)

    print('lavel = ',lavel,'training 準確率:',accuracy)
    

Epoch 1/25
13705/13705 [==============================] - 1s 43us/step - loss: 0.8969 - accuracy: 0.5805
Epoch 2/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.7732 - accuracy: 0.6547
Epoch 3/25
13705/13705 [==============================] - 0s 36us/step - loss: 0.7632 - accuracy: 0.6600
Epoch 4/25
13705/13705 [==============================] - 0s 36us/step - loss: 0.7563 - accuracy: 0.6645
Epoch 5/25
13705/13705 [==============================] - 1s 39us/step - loss: 0.7506 - accuracy: 0.6673
Epoch 6/25
13705/13705 [==============================] - 1s 39us/step - loss: 0.7455 - accuracy: 0.6703
Epoch 7/25
13705/13705 [==============================] - 1s 39us/step - loss: 0.7400 - accuracy: 0.6733
Epoch 8/25
13705/13705 [==============================] - 1s 38us/step - loss: 0.7352 - accuracy: 0.6753
Epoch 9/25
13705/13705 [==============================] - 1s 39us/step - loss: 0.7285 - accuracy: 0.6760
Epoch 10/25
13705/13705 [==============================

ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets

In [17]:
def deep_model(i):
    model = Sequential()
    model.add(Dense(64, input_dim=141, activation='sigmoid'))
    for k in range(i):
      model.add(Dense(64,activation='sigmoid'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

for lavel in range(1,2):
   model = deep_model(lavel)
   model.fit(x_train_nor, y_train,epochs=25,verbose=1)
   y_test_predicted = model.predict(x_test_nor)
   print(y_test_predicted.shape[0])
   #  pdct = []
   #  for i in range(int(y_test_predicted.shape[0])):
   #      if (y_test_predicted[i,0] > y_test_predicted[i,1]):
   #          pdct.append(int(0))
   #      else:
   #          pdct.append(int(1))
   y_test_predicted = (y_test_predicted > 0.5)
   print (y_test_predicted)
   accuracy = accuracy_score(y_test, y_test_predicted)

   print('lavel = ',lavel,'training 準確率:',accuracy)
    

Epoch 1/25
13705/13705 [==============================] - 1s 49us/step - loss: 0.9234 - accuracy: 0.5697
Epoch 2/25
13705/13705 [==============================] - 1s 39us/step - loss: 0.7792 - accuracy: 0.6514
Epoch 3/25
13705/13705 [==============================] - 1s 39us/step - loss: 0.7652 - accuracy: 0.6569
Epoch 4/25
13705/13705 [==============================] - 1s 40us/step - loss: 0.7599 - accuracy: 0.6625
Epoch 5/25
13705/13705 [==============================] - 1s 42us/step - loss: 0.7539 - accuracy: 0.6645
Epoch 6/25
13705/13705 [==============================] - 1s 40us/step - loss: 0.7480 - accuracy: 0.6660
Epoch 7/25
13705/13705 [==============================] - 1s 39us/step - loss: 0.7439 - accuracy: 0.6702
Epoch 8/25
13705/13705 [==============================] - 1s 40us/step - loss: 0.7387 - accuracy: 0.6743
Epoch 9/25
13705/13705 [==============================] - 1s 41us/step - loss: 0.7327 - accuracy: 0.6771
Epoch 10/25
13705/13705 [==============================

In [18]:
def deep_model(i):
    model = Sequential()
    model.add(Dense(64, input_dim=141, activation='sigmoid'))
    for k in range(i):
      model.add(Dense(64,activation='sigmoid'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

for lavel in range(1,2):
   model = deep_model(lavel)
   model.fit(x_train_nor, y_train,epochs=25,verbose=1)
   y_test_predicted = model.predict(x_test_nor)
   print(y_test_predicted.shape[0])
   #  pdct = []
   #  for i in range(int(y_test_predicted.shape[0])):
   #      if (y_test_predicted[i,0] > y_test_predicted[i,1]):
   #          pdct.append(int(0))
   #      else:
   #          pdct.append(int(1))
   y_test_predicted = (y_test_predicted > 0.5)
   print (y_test_predicted)
   print ( y_test)
   accuracy = accuracy_score(y_test, y_test_predicted)

   print('lavel = ',lavel,'training 準確率:',accuracy)
    

Epoch 1/25
13705/13705 [==============================] - 1s 48us/step - loss: 0.8975 - accuracy: 0.5839
Epoch 2/25
13705/13705 [==============================] - 1s 40us/step - loss: 0.7748 - accuracy: 0.6530
Epoch 3/25
13705/13705 [==============================] - 1s 40us/step - loss: 0.7630 - accuracy: 0.6595
Epoch 4/25
13705/13705 [==============================] - 1s 40us/step - loss: 0.7573 - accuracy: 0.6635
Epoch 5/25
13705/13705 [==============================] - 1s 40us/step - loss: 0.7522 - accuracy: 0.6641
Epoch 6/25
13705/13705 [==============================] - 1s 38us/step - loss: 0.7475 - accuracy: 0.6685
Epoch 7/25
13705/13705 [==============================] - 1s 37us/step - loss: 0.7425 - accuracy: 0.6716
Epoch 8/25
13705/13705 [==============================] - 1s 38us/step - loss: 0.7367 - accuracy: 0.6725
Epoch 9/25
13705/13705 [==============================] - 1s 37us/step - loss: 0.7303 - accuracy: 0.6795
Epoch 10/25
13705/13705 [==============================

In [19]:
def deep_model(i):
    model = Sequential()
    model.add(Dense(64, input_dim=141, activation='sigmoid'))
    for k in range(i):
      model.add(Dense(64,activation='sigmoid'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

for lavel in range(1,10):
   model = deep_model(lavel)
   model.fit(x_train_nor, y_train,epochs=25,verbose=1)
   y_test_predicted = model.predict(x_test_nor)
   print(y_test_predicted.shape[0])
   #  pdct = []
   #  for i in range(int(y_test_predicted.shape[0])):
   #      if (y_test_predicted[i,0] > y_test_predicted[i,1]):
   #          pdct.append(int(0))
   #      else:
   #          pdct.append(int(1))
   y_test_predicted = (y_test_predicted > 0.5)
   print (y_test_predicted)
   print ( y_test)
   accuracy = accuracy_score(y_test, y_test_predicted)

   print('lavel = ',lavel,'training 準確率:',accuracy)
    

Epoch 1/25
13705/13705 [==============================] - 1s 49us/step - loss: 0.8936 - accuracy: 0.5870
Epoch 2/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.7749 - accuracy: 0.6524
Epoch 3/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.7641 - accuracy: 0.6602
Epoch 4/25
13705/13705 [==============================] - 1s 37us/step - loss: 0.7587 - accuracy: 0.6638
Epoch 5/25
13705/13705 [==============================] - 1s 38us/step - loss: 0.7537 - accuracy: 0.6636
Epoch 6/25
13705/13705 [==============================] - 1s 37us/step - loss: 0.7480 - accuracy: 0.6686
Epoch 7/25
13705/13705 [==============================] - 1s 36us/step - loss: 0.7433 - accuracy: 0.6721
Epoch 8/25
13705/13705 [==============================] - 0s 36us/step - loss: 0.7389 - accuracy: 0.6730
Epoch 9/25
13705/13705 [==============================] - 1s 37us/step - loss: 0.7318 - accuracy: 0.6768
Epoch 10/25
13705/13705 [==============================

KeyboardInterrupt: 

In [20]:
def deep_model(i):
    model = Sequential()
    model.add(Dense(64, input_dim=141, activation='sigmoid'))
    for k in range(i):
      model.add(Dense(64,activation='sigmoid'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

for lavel in range(1,10):
   model = deep_model(lavel)
   model.fit(x_train_nor, y_train,epochs=25,verbose=1)
   y_test_predicted = model.predict(x_test_nor)
   print(y_test_predicted.shape[0])
   #  pdct = []
   #  for i in range(int(y_test_predicted.shape[0])):
   #      if (y_test_predicted[i,0] > y_test_predicted[i,1]):
   #          pdct.append(int(0))
   #      else:
   #          pdct.append(int(1))
   y_test_predicted = (y_test_predicted > 0.5)

   accuracy = accuracy_score(y_test, y_test_predicted)

   print('lavel = ',lavel,'training 準確率:',accuracy)
    

==============] - 1s 41us/step - loss: 0.6790 - accuracy: 0.7050
Epoch 16/25
13705/13705 [==============================] - 1s 42us/step - loss: 0.6661 - accuracy: 0.7105
Epoch 17/25
13705/13705 [==============================] - 1s 42us/step - loss: 0.6555 - accuracy: 0.7201
Epoch 18/25
13705/13705 [==============================] - 1s 37us/step - loss: 0.6398 - accuracy: 0.7243
Epoch 19/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.6258 - accuracy: 0.7331
Epoch 20/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.6122 - accuracy: 0.7422
Epoch 21/25
13705/13705 [==============================] - 0s 36us/step - loss: 0.5938 - accuracy: 0.7545
Epoch 22/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.5721 - accuracy: 0.7619
Epoch 23/25
13705/13705 [==============================] - 0s 34us/step - loss: 0.5569 - accuracy: 0.7673
Epoch 24/25
13705/13705 [==============================] - 0s 35us/step - loss: 0.5418 